[tool.commitizen]
name = "cz_customize"
tag_format = "$version"
version_scheme = "semver"
version_provider = "npm"
update_changelog_on_bump = true
major_version_zero = true

[tool.commitizen.customize]
message_template = "{{change_type}}"

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = [
{value = ":bug:", name = "fix: A bug fix. Correlates with PATCH in SemVer"}
{value = ":feat:", name = "feat: A new feature. Correlates with MINOR in SemVer"},
{value = ":memo:", name = "Documentation only changes"},
{value = ":style:", name = ""},
{value = "refactor", name = ""},
{value = "perf", name = ""},
{value = "test", name = ""},
{value = "build", name = ""},
{value = "ci", name = ""},
{value = ":alien", name = ""}
]
# choices = ["feature", "fix"]  # short version
message = "Select the type of change you are committing"
